on:
  pull_request_target:
    types:
      - closed
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.5.0
      - name: Set up Python
        uses: actions/setup-python@4.3.0
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Generate site content
        run: make publish
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: output
  deploy:
    needs: upload
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: '${{steps.deployment.outputs.page_url}}'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v1.2.2
